spring:
  datasource:
    url: jdbc:h2:mem:todo-app
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true

todo-app:
  security:
    csrf-enabled: false